name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select test to run
          required: True
            type: choice
              default: all
                options:
                  - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
      steps:
        - name: Copy source code
          users: actions/checkout@v4
        - name: Set up Python env
          users: actions/setup-python@v5
          with:
            python-version: "3.13"
        - name: install dependecies
          run: pip install -r requirements.txt
        - name: Run tests
          run: pytest -v
